version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: cancha_db
      POSTGRES_USER: cancha_db_user
      POSTGRES_PASSWORD: cancha_db_password
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: